---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart xray
  ansible.builtin.systemd:
    name: xray
    state: restarted

- name: Restart nftables
  ansible.builtin.systemd:
    name: nftables
    state: restarted
