from typing import TYPE_CHECKING

from sqlalchemy import JSON, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.vpn_server import VPNServer


class VLESSServerConfig(Base, TimestampMixin):
    """VLESS/Reality-specific server data, 1:1 with a `VPNServer` row whose
    `protocol == VPNProtocol.VLESS` — deliberately a separate table rather than new
    columns on `VPNServer` or (worse) `VPNPeer`, since none of this data applies to a
    WireGuard server and none of WireGuard's server fields apply here (see
    docs/vless.md).

    `reality_public_key` is the ONLY Reality key material that ever reaches the
    backend/Postgres — the private key lives exclusively on the exit node's filesystem,
    generated by Ansible (infrastructure/ansible/roles/xray) and read directly by
    Xray-core; it is never transmitted here. See docs/xray-agent.md's security section.
    """

    __tablename__ = "vless_server_configs"

    id: Mapped[int] = mapped_column(primary_key=True)
    server_id: Mapped[int] = mapped_column(
        ForeignKey("vpn_servers.id", ondelete="CASCADE"), unique=True, index=True
    )
    xray_agent_base_url: Mapped[str] = mapped_column(String(255), nullable=False)
    port: Mapped[int] = mapped_column(Integer, default=443, nullable=False)
    reality_public_key: Mapped[str] = mapped_column(String(64), nullable=False)
    reality_short_ids: Mapped[list[str]] = mapped_column(JSON, nullable=False, default=list)
    sni: Mapped[str] = mapped_column(String(255), nullable=False)
    fingerprint: Mapped[str] = mapped_column(String(32), default="chrome", nullable=False)
    flow: Mapped[str] = mapped_column(String(32), default="xtls-rprx-vision", nullable=False)
    network_type: Mapped[str] = mapped_column(String(16), default="tcp", nullable=False)

    server: Mapped["VPNServer"] = relationship()
