from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, Enum, ForeignKey, String, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin
from app.models.enums import VLESSCredentialStatus

if TYPE_CHECKING:
    from app.models.device import Device
    from app.models.vpn_server import VPNServer


class VLESSCredential(Base, TimestampMixin):
    """A device's VLESS identity on one VLESS server — the VLESS analogue of `VPNPeer`,
    deliberately a separate model rather than reusing `VPNPeer` (see docs/vless.md):
    VLESS has no IP allocation, no keypair, and its per-user identity (a UUID) is
    generated by the backend, not returned once from an agent call the way a WireGuard
    private key is.

    `device_id` is NOT unique alone — a device may hold one credential per VLESS server
    (see the UniqueConstraint below), which is what makes multi-node support (multiple
    VLESSCredential rows for one device, one per server) representable without a schema
    change later; MVP only ever creates one, but SubscriptionDeliveryService/
    VLESSFormatter already iterate over "however many a device has" (see
    app/services/subscription_delivery/formatters/vless_formatter.py).
    """

    __tablename__ = "vless_credentials"

    id: Mapped[int] = mapped_column(primary_key=True)
    device_id: Mapped[int] = mapped_column(ForeignKey("devices.id", ondelete="CASCADE"), index=True)
    server_id: Mapped[int] = mapped_column(ForeignKey("vpn_servers.id", ondelete="CASCADE"))
    uuid: Mapped[str] = mapped_column(String(36), unique=True, nullable=False, index=True)
    status: Mapped[VLESSCredentialStatus] = mapped_column(
        Enum(VLESSCredentialStatus, native_enum=False),
        default=VLESSCredentialStatus.ACTIVE,
        nullable=False,
        index=True,
    )
    rotated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    device: Mapped["Device"] = relationship()
    server: Mapped["VPNServer"] = relationship()

    __table_args__ = (
        UniqueConstraint("device_id", "server_id", name="uq_vless_credential_device_server"),
    )
