# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: command.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.xray_proto import user_pb2 as user__pb2
from app.xray_proto import typed_message_pb2 as typed__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcommand.proto\x12\x19xray.app.proxyman.command\x1a\nuser.proto\x1a\x13typed_message.proto\"<\n\x10\x41\x64\x64UserOperation\x12(\n\x04user\x18\x01 \x01(\x0b\x32\x1a.xray.common.protocol.User\"$\n\x13RemoveUserOperation\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"W\n\x13\x41lterInboundRequest\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x33\n\toperation\x18\x02 \x01(\x0b\x32 .xray.common.serial.TypedMessage\"\x16\n\x14\x41lterInboundResponse\"3\n\x15GetInboundUserRequest\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"C\n\x16GetInboundUserResponse\x12)\n\x05users\x18\x01 \x03(\x0b\x32\x1a.xray.common.protocol.User\"-\n\x1cGetInboundUsersCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x32\x83\x03\n\x0eHandlerService\x12q\n\x0c\x41lterInbound\x12..xray.app.proxyman.command.AlterInboundRequest\x1a/.xray.app.proxyman.command.AlterInboundResponse\"\x00\x12x\n\x0fGetInboundUsers\x12\x30.xray.app.proxyman.command.GetInboundUserRequest\x1a\x31.xray.app.proxyman.command.GetInboundUserResponse\"\x00\x12\x83\x01\n\x14GetInboundUsersCount\x12\x30.xray.app.proxyman.command.GetInboundUserRequest\x1a\x37.xray.app.proxyman.command.GetInboundUsersCountResponse\"\x00\x42\x30Z.github.com/xtls/xray-core/app/proxyman/commandb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/xtls/xray-core/app/proxyman/command'
  _globals['_ADDUSEROPERATION']._serialized_start=77
  _globals['_ADDUSEROPERATION']._serialized_end=137
  _globals['_REMOVEUSEROPERATION']._serialized_start=139
  _globals['_REMOVEUSEROPERATION']._serialized_end=175
  _globals['_ALTERINBOUNDREQUEST']._serialized_start=177
  _globals['_ALTERINBOUNDREQUEST']._serialized_end=264
  _globals['_ALTERINBOUNDRESPONSE']._serialized_start=266
  _globals['_ALTERINBOUNDRESPONSE']._serialized_end=288
  _globals['_GETINBOUNDUSERREQUEST']._serialized_start=290
  _globals['_GETINBOUNDUSERREQUEST']._serialized_end=341
  _globals['_GETINBOUNDUSERRESPONSE']._serialized_start=343
  _globals['_GETINBOUNDUSERRESPONSE']._serialized_end=410
  _globals['_GETINBOUNDUSERSCOUNTRESPONSE']._serialized_start=412
  _globals['_GETINBOUNDUSERSCOUNTRESPONSE']._serialized_end=457
  _globals['_HANDLERSERVICE']._serialized_start=460
  _globals['_HANDLERSERVICE']._serialized_end=847
# @@protoc_insertion_point(module_scope)
