"""VLESS user-lifecycle abstraction — the VLESS analogue of `app.services.vpn.provider`,
deliberately a separate, differently-shaped Protocol rather than an extension of
`VPNProvider`.

WireGuard's `VPNProvider` centers on "create/delete/disable/enable a *peer*" plus
rendering a client config from key material returned once. VLESS has no keypair, no IP
allocation, and no per-peer client-config rendering step here at all (that's
VLESSFormatter, downstream in subscription delivery) — its actual operations are
UUID-keyed user lifecycle calls against xray-agent. Forcing these into one shared
interface today would either bloat `VPNProvider` with VLESS-only concerns or leave
WireGuard-only concerns on a `VLESSProvider` that never uses them — see docs/vless.md's
architecture-comparison section for why this stays two protocols, not one premature
abstraction, until a genuine third transport makes the real commonalities visible.

UUIDs are generated by the *backend* (app.services.device_service), never by
xray-agent — see docs/xray-agent.md.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Protocol

from app.models.vless_server_config import VLESSServerConfig


@dataclass(frozen=True, slots=True)
class VLESSUserRecord:
    uuid: str
    device_id: int
    flow: str
    created_at: datetime
    rotated_at: datetime | None


class XrayAgentProvider(Protocol):
    async def create_user(
        self, *, server_config: VLESSServerConfig, uuid: str, device_id: int, flow: str
    ) -> VLESSUserRecord:
        """Idempotent — safe to retry and safe to call again with the same uuid (e.g.
        to re-enable a previously disabled credential without rotating it)."""
        ...

    async def remove_user(self, *, server_config: VLESSServerConfig, uuid: str) -> None:
        """Idempotent — removing an already-absent uuid is not an error."""
        ...

    async def rotate_user(
        self, *, server_config: VLESSServerConfig, uuid: str, new_uuid: str
    ) -> VLESSUserRecord: ...

    async def list_users(self, *, server_config: VLESSServerConfig) -> list[VLESSUserRecord]: ...

    async def health_check(self, *, server_config: VLESSServerConfig) -> bool:
        """True only if xray-agent is reachable AND reports Xray itself as reachable
        (see xray-agent's GET /ready) — not just that the HTTP call succeeded."""
        ...
